defmodule Podcaster.Repo.Migrations.PodcastEpisodeTranscript do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:shows) do
      remove :num_of_episodes
    end

    alter table(:episodes) do
      modify :url, :text, null: false
      modify :title, :text, null: false
      add :transcript, {:array, :map}
    end
  end

  def down do
    alter table(:episodes) do
      remove :transcript
      modify :title, :text, null: true
      modify :url, :text, null: true
    end

    alter table(:shows) do
      add :num_of_episodes, :bigint, default: 0
    end
  end
end
