defmodule Podcaster.Repo.Migrations.PodcastShowUniqueUrl do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:shows), :name, to: :title

    alter table(:shows) do
      modify :title, :citext
      add :num_of_episodes, :bigint, default: 0
    end

    create unique_index(:shows, [:url], name: "shows_unique_url_index")
  end

  def down do
    alter table(:shows) do
      remove :num_of_episodes
      modify :name, :text
    end

    rename table(:shows), :title, to: :name

    drop_if_exists unique_index(:shows, [:url], name: "shows_unique_url_index")
  end
end
