defmodule Podcaster.Repo.Migrations.EpisodePublishDate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:episodes) do
      add :publish_date, :utc_datetime
    end
  end

  def down do
    alter table(:episodes) do
      remove :publish_date
    end
  end
end
