defmodule Podcaster.Repo.Migrations.PodcastEpisodeUniqueUrl do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:episodes, [:url], name: "episodes_unique_url_index")
  end

  def down do
    drop_if_exists unique_index(:episodes, [:url], name: "episodes_unique_url_index")
  end
end
